"""Curated English-language nutrition estimates for common Indian foods.

Values are approximate per 100 g and are intended to make everyday dish
logging discoverable even when packaged-food databases have sparse coverage.
"""

INDIAN_FOOD_CATALOG = [
    {"name": "Paneer", "calories": 265, "protein": 18.3, "carbs": 1.2, "fat": 20.8, "fiber": 0, "sugar": 1.2, "sodium": 22, "tags": ["paneer", "cottage cheese"]},
    {"name": "Chapati / Roti", "calories": 120, "protein": 3.5, "carbs": 18, "fat": 3.7, "fiber": 3, "sugar": 0.5, "sodium": 120, "tags": ["chapati", "roti", "phulka", "flatbread", "bread"]},
    {"name": "Plain Dosa", "calories": 168, "protein": 3.9, "carbs": 29.5, "fat": 3.7, "fiber": 1.2, "sugar": 0.4, "sodium": 210, "tags": ["dosa", "dosai", "plain dosa", "south indian"]},
    {"name": "Masala Dosa", "calories": 206, "protein": 4.5, "carbs": 30, "fat": 7.5, "fiber": 2.2, "sugar": 1.5, "sodium": 310, "tags": ["dosa", "masala dosa", "potato dosa", "south indian"]},
    {"name": "Rava Dosa", "calories": 190, "protein": 4.1, "carbs": 31, "fat": 5.5, "fiber": 1.4, "sugar": 0.6, "sodium": 280, "tags": ["dosa", "rava dosa", "suji dosa", "south indian"]},
    {"name": "Mysore Masala Dosa", "calories": 215, "protein": 4.8, "carbs": 31, "fat": 8.2, "fiber": 2.4, "sugar": 1.8, "sodium": 340, "tags": ["dosa", "mysore dosa", "mysore masala dosa", "south indian"]},
    {"name": "Set Dosa", "calories": 170, "protein": 4.2, "carbs": 31, "fat": 3.2, "fiber": 1.3, "sugar": 0.8, "sodium": 220, "tags": ["dosa", "set dosa", "south indian"]},
    {"name": "Neer Dosa", "calories": 140, "protein": 2.4, "carbs": 29, "fat": 1.5, "fiber": 0.8, "sugar": 0.2, "sodium": 150, "tags": ["dosa", "neer dosa", "mangalorean", "south indian"]},
    {"name": "Idli", "calories": 146, "protein": 4.5, "carbs": 28.7, "fat": 0.7, "fiber": 1.2, "sugar": 0.3, "sodium": 160, "tags": ["idli", "steamed rice cake", "south indian", "breakfast"]},
    {"name": "Sambar", "calories": 76, "protein": 3.5, "carbs": 10.5, "fat": 2.4, "fiber": 3.2, "sugar": 2.1, "sodium": 290, "tags": ["sambar", "sambhar", "lentil curry", "south indian"]},
    {"name": "Medu Vada", "calories": 220, "protein": 8.5, "carbs": 28, "fat": 8.5, "fiber": 4.2, "sugar": 1.2, "sodium": 330, "tags": ["vada", "medu vada", "urad vada", "south indian"]},
    {"name": "Uttapam", "calories": 180, "protein": 4.8, "carbs": 30, "fat": 4.8, "fiber": 2.1, "sugar": 1.6, "sodium": 250, "tags": ["uttapam", "uthappam", "south indian", "breakfast"]},
    {"name": "Vegetable Upma", "calories": 120, "protein": 3.5, "carbs": 22, "fat": 2.7, "fiber": 2.3, "sugar": 1.4, "sodium": 260, "tags": ["upma", "vegetable upma", "suji", "semolina", "breakfast"]},
    {"name": "Vegetable Poha", "calories": 130, "protein": 2.6, "carbs": 24.6, "fat": 2.6, "fiber": 2.1, "sugar": 1.3, "sodium": 230, "tags": ["poha", "aval", "flattened rice", "breakfast"]},
    {"name": "Appam", "calories": 135, "protein": 2.5, "carbs": 28, "fat": 1.5, "fiber": 0.8, "sugar": 1.2, "sodium": 120, "tags": ["appam", "rice pancake", "kerala", "south indian"]},
    {"name": "Pongal", "calories": 145, "protein": 4.5, "carbs": 23, "fat": 4.2, "fiber": 2, "sugar": 0.8, "sodium": 260, "tags": ["pongal", "ven pongal", "rice lentil", "south indian"]},
    {"name": "Plain Paratha", "calories": 260, "protein": 7, "carbs": 40, "fat": 8, "fiber": 5, "sugar": 1.2, "sodium": 330, "tags": ["paratha", "parantha", "flatbread", "bread"]},
    {"name": "Aloo Paratha", "calories": 210, "protein": 5, "carbs": 33, "fat": 7, "fiber": 4.1, "sugar": 1.5, "sodium": 360, "tags": ["aloo paratha", "potato paratha", "parantha", "flatbread"]},
    {"name": "Naan", "calories": 262, "protein": 8.7, "carbs": 45.4, "fat": 5.1, "fiber": 2.2, "sugar": 3.2, "sodium": 420, "tags": ["naan", "flatbread", "bread", "tandoori bread"]},
    {"name": "Puri", "calories": 296, "protein": 6.5, "carbs": 42, "fat": 11, "fiber": 3.5, "sugar": 0.7, "sodium": 320, "tags": ["puri", "poori", "fried bread", "bread"]},
    {"name": "Bhatura", "calories": 320, "protein": 7.2, "carbs": 46, "fat": 12.5, "fiber": 2.5, "sugar": 2.2, "sodium": 410, "tags": ["bhatura", "chole bhature", "fried bread", "bread"]},
    {"name": "Dal Tadka", "calories": 135, "protein": 6.2, "carbs": 18, "fat": 4.3, "fiber": 5.4, "sugar": 1.8, "sodium": 310, "tags": ["dal", "dal tadka", "yellow dal", "lentil curry"]},
    {"name": "Dal Makhani", "calories": 170, "protein": 6.5, "carbs": 16, "fat": 9, "fiber": 5, "sugar": 2.1, "sodium": 340, "tags": ["dal", "dal makhani", "black dal", "lentil curry"]},
    {"name": "Rajma Masala", "calories": 127, "protein": 8.7, "carbs": 22.8, "fat": 0.5, "fiber": 6.4, "sugar": 1.3, "sodium": 260, "tags": ["rajma", "kidney beans", "rajma masala", "bean curry"]},
    {"name": "Chole / Chana Masala", "calories": 164, "protein": 8.9, "carbs": 27.4, "fat": 2.6, "fiber": 7.6, "sugar": 4.8, "sodium": 300, "tags": ["chole", "chana", "chana masala", "chickpea curry"]},
    {"name": "Palak Paneer", "calories": 180, "protein": 10, "carbs": 7, "fat": 13, "fiber": 2.4, "sugar": 2.2, "sodium": 350, "tags": ["palak paneer", "paneer", "spinach curry"]},
    {"name": "Paneer Butter Masala", "calories": 220, "protein": 9, "carbs": 10, "fat": 17, "fiber": 1.8, "sugar": 4.5, "sodium": 390, "tags": ["paneer butter masala", "butter paneer", "paneer makhani", "paneer curry"]},
    {"name": "Shahi Paneer", "calories": 250, "protein": 9, "carbs": 11, "fat": 19, "fiber": 1.5, "sugar": 4.8, "sodium": 370, "tags": ["shahi paneer", "paneer", "paneer curry"]},
    {"name": "Paneer Tikka", "calories": 190, "protein": 17, "carbs": 6, "fat": 11, "fiber": 1.2, "sugar": 2.5, "sodium": 360, "tags": ["paneer tikka", "paneer", "tandoori paneer", "starter"]},
    {"name": "Matar Paneer", "calories": 175, "protein": 9, "carbs": 10, "fat": 11.5, "fiber": 3.2, "sugar": 3.5, "sodium": 330, "tags": ["matar paneer", "paneer", "peas paneer", "paneer curry"]},
    {"name": "Aloo Gobi", "calories": 110, "protein": 3.2, "carbs": 15, "fat": 4.5, "fiber": 3.4, "sugar": 2.7, "sodium": 260, "tags": ["aloo gobi", "potato cauliflower", "sabzi", "vegetable curry"]},
    {"name": "Bhindi Masala", "calories": 115, "protein": 3, "carbs": 12, "fat": 6.5, "fiber": 4.1, "sugar": 3.2, "sodium": 250, "tags": ["bhindi", "okra", "bhindi masala", "sabzi"]},
    {"name": "Baingan Bharta", "calories": 105, "protein": 2.3, "carbs": 11, "fat": 6, "fiber": 4, "sugar": 5, "sodium": 260, "tags": ["baingan bharta", "eggplant", "brinjal", "sabzi"]},
    {"name": "Mixed Vegetable Sabzi", "calories": 95, "protein": 3, "carbs": 13, "fat": 4, "fiber": 4, "sugar": 4, "sodium": 240, "tags": ["sabzi", "vegetable curry", "mixed vegetables", "veg curry"]},
    {"name": "Chicken Curry", "calories": 180, "protein": 20, "carbs": 5, "fat": 9, "fiber": 1, "sugar": 2.2, "sodium": 380, "tags": ["chicken curry", "chicken", "murgh curry"]},
    {"name": "Butter Chicken", "calories": 210, "protein": 18, "carbs": 7, "fat": 13, "fiber": 1, "sugar": 3.5, "sodium": 420, "tags": ["butter chicken", "murgh makhani", "chicken curry"]},
    {"name": "Chicken Tikka", "calories": 180, "protein": 27, "carbs": 4, "fat": 6, "fiber": 0.8, "sugar": 2, "sodium": 410, "tags": ["chicken tikka", "tandoori chicken", "chicken", "starter"]},
    {"name": "Egg Curry", "calories": 155, "protein": 9.5, "carbs": 6, "fat": 10.5, "fiber": 1.2, "sugar": 2.5, "sodium": 360, "tags": ["egg curry", "anda curry", "egg"]},
    {"name": "Egg Bhurji", "calories": 165, "protein": 11, "carbs": 4, "fat": 12, "fiber": 0.8, "sugar": 2, "sodium": 330, "tags": ["egg bhurji", "anda bhurji", "scrambled egg", "egg"]},
    {"name": "Plain Omelette", "calories": 154, "protein": 11, "carbs": 1.6, "fat": 11.5, "fiber": 0, "sugar": 1.1, "sodium": 280, "tags": ["omelette", "omelet", "omlette", "plain omelette", "egg", "breakfast"]},
    {"name": "Masala Omelette", "calories": 160, "protein": 10.5, "carbs": 4, "fat": 11, "fiber": 0.8, "sugar": 2, "sodium": 330, "tags": ["omelette", "omelet", "omlette", "masala omelette", "indian omelette", "egg", "breakfast"]},
    {"name": "Vegetable Omelette", "calories": 150, "protein": 10, "carbs": 5, "fat": 9.5, "fiber": 1.2, "sugar": 2.4, "sodium": 300, "tags": ["omelette", "omelet", "omlette", "vegetable omelette", "veg omelette", "egg", "breakfast"]},
    {"name": "Cheese Omelette", "calories": 210, "protein": 14, "carbs": 2.5, "fat": 16, "fiber": 0, "sugar": 1.4, "sodium": 430, "tags": ["omelette", "omelet", "omlette", "cheese omelette", "egg", "breakfast"]},
    {"name": "Egg White Omelette", "calories": 100, "protein": 17, "carbs": 3, "fat": 2, "fiber": 0.8, "sugar": 1.5, "sodium": 310, "tags": ["omelette", "omelet", "omlette", "egg white omelette", "high protein", "breakfast"]},
    {"name": "Bread Omelette", "calories": 210, "protein": 10, "carbs": 20, "fat": 10, "fiber": 1.5, "sugar": 2.5, "sodium": 390, "tags": ["omelette", "omelet", "omlette", "bread omelette", "egg sandwich", "breakfast"]},
    {"name": "Fish Curry", "calories": 150, "protein": 18, "carbs": 5, "fat": 7, "fiber": 1, "sugar": 2, "sodium": 390, "tags": ["fish curry", "machli curry", "seafood"]},
    {"name": "Chicken Biryani", "calories": 170, "protein": 9, "carbs": 24, "fat": 4.5, "fiber": 1.2, "sugar": 1.3, "sodium": 350, "tags": ["biryani", "chicken biryani", "rice", "hyderabadi"]},
    {"name": "Vegetable Biryani", "calories": 150, "protein": 3.5, "carbs": 28, "fat": 3, "fiber": 2.5, "sugar": 2, "sodium": 320, "tags": ["biryani", "veg biryani", "vegetable biryani", "rice"]},
    {"name": "Mutton Biryani", "calories": 190, "protein": 10, "carbs": 23, "fat": 6.5, "fiber": 1.1, "sugar": 1.2, "sodium": 380, "tags": ["biryani", "mutton biryani", "lamb biryani", "rice"]},
    {"name": "Egg Biryani", "calories": 175, "protein": 7, "carbs": 25, "fat": 5.2, "fiber": 1.2, "sugar": 1.3, "sodium": 360, "tags": ["biryani", "egg biryani", "anda biryani", "rice"]},
    {"name": "Vegetable Pulao", "calories": 160, "protein": 3.5, "carbs": 29, "fat": 3.5, "fiber": 2.2, "sugar": 1.8, "sodium": 280, "tags": ["pulao", "pilaf", "veg pulao", "rice"]},
    {"name": "Lemon Rice", "calories": 175, "protein": 3.5, "carbs": 30, "fat": 4.5, "fiber": 1.7, "sugar": 1, "sodium": 290, "tags": ["lemon rice", "rice", "south indian"]},
    {"name": "Curd Rice", "calories": 140, "protein": 4, "carbs": 23, "fat": 3.5, "fiber": 0.8, "sugar": 2.2, "sodium": 220, "tags": ["curd rice", "yogurt rice", "dahi rice", "rice"]},
    {"name": "Moong Dal Khichdi", "calories": 120, "protein": 4.5, "carbs": 20, "fat": 2.5, "fiber": 2.8, "sugar": 0.8, "sodium": 230, "tags": ["khichdi", "khichri", "moong dal khichdi", "rice lentil"]},
    {"name": "Cooked White Rice", "calories": 130, "protein": 2.7, "carbs": 28.2, "fat": 0.3, "fiber": 0.4, "sugar": 0.1, "sodium": 1, "tags": ["rice", "white rice", "chawal", "steamed rice"]},
    {"name": "Pav Bhaji", "calories": 165, "protein": 4.5, "carbs": 27, "fat": 5, "fiber": 3.5, "sugar": 4, "sodium": 400, "tags": ["pav bhaji", "street food", "mumbai"]},
    {"name": "Vada Pav", "calories": 250, "protein": 6, "carbs": 40, "fat": 8, "fiber": 3.5, "sugar": 3, "sodium": 430, "tags": ["vada pav", "street food", "mumbai", "bread"]},
    {"name": "Vegetable Samosa", "calories": 262, "protein": 5, "carbs": 32, "fat": 13, "fiber": 3, "sugar": 2, "sodium": 380, "tags": ["samosa", "vegetable samosa", "snack", "street food"]},
    {"name": "Kachori", "calories": 300, "protein": 7, "carbs": 36, "fat": 14, "fiber": 4, "sugar": 2, "sodium": 420, "tags": ["kachori", "snack", "street food"]},
    {"name": "Vegetable Pakora", "calories": 280, "protein": 6, "carbs": 30, "fat": 15, "fiber": 4, "sugar": 3, "sodium": 390, "tags": ["pakora", "pakoda", "bhajiya", "fritter", "snack"]},
    {"name": "Dhokla", "calories": 160, "protein": 6, "carbs": 25, "fat": 4, "fiber": 3, "sugar": 5, "sodium": 370, "tags": ["dhokla", "khaman", "gujarati", "snack"]},
    {"name": "Bhel Puri", "calories": 190, "protein": 5, "carbs": 34, "fat": 4, "fiber": 4.5, "sugar": 5, "sodium": 410, "tags": ["bhel puri", "bhel", "chaat", "street food"]},
    {"name": "Pani Puri", "calories": 180, "protein": 4.5, "carbs": 32, "fat": 4.2, "fiber": 3.5, "sugar": 3, "sodium": 430, "tags": ["pani puri", "golgappa", "puchka", "chaat", "street food"]},
    {"name": "Whole Wheat Bread", "calories": 247, "protein": 13, "carbs": 41, "fat": 4.2, "fiber": 7, "sugar": 6, "sodium": 430, "tags": ["bread", "whole wheat bread", "brown bread", "atta bread"]},
    {"name": "White Bread", "calories": 265, "protein": 9, "carbs": 49, "fat": 3.2, "fiber": 2.7, "sugar": 5, "sodium": 490, "tags": ["bread", "white bread", "sandwich bread"]},
    {"name": "Tandoori Roti", "calories": 230, "protein": 7.5, "carbs": 43, "fat": 3.2, "fiber": 5, "sugar": 1.2, "sodium": 310, "tags": ["roti", "tandoori roti", "flatbread", "bread"]},
    {"name": "Jowar Roti", "calories": 210, "protein": 6.5, "carbs": 43, "fat": 2.2, "fiber": 6.5, "sugar": 1.5, "sodium": 180, "tags": ["roti", "jowar roti", "sorghum roti", "bhakri", "flatbread"]},
    {"name": "Bajra Roti", "calories": 220, "protein": 6.8, "carbs": 42, "fat": 3.5, "fiber": 7, "sugar": 1.4, "sodium": 190, "tags": ["roti", "bajra roti", "pearl millet roti", "bhakri", "flatbread"]},
    {"name": "Boiled Egg", "calories": 155, "protein": 12.6, "carbs": 1.1, "fat": 10.6, "fiber": 0, "sugar": 1.1, "sodium": 124, "tags": ["egg", "boiled egg", "anda"]},
    {"name": "Chicken Breast", "calories": 165, "protein": 31, "carbs": 0, "fat": 3.6, "fiber": 0, "sugar": 0, "sodium": 74, "tags": ["chicken", "chicken breast"]},
    {"name": "Curd / Yogurt", "calories": 61, "protein": 3.5, "carbs": 4.7, "fat": 3.3, "fiber": 0, "sugar": 4.7, "sodium": 46, "tags": ["curd", "yogurt", "dahi"]},
    {"name": "Oats", "calories": 389, "protein": 16.9, "carbs": 66.3, "fat": 6.9, "fiber": 10.6, "sugar": 0.9, "sodium": 2, "tags": ["oats", "oatmeal"]},
    {"name": "Banana", "calories": 89, "protein": 1.1, "carbs": 22.8, "fat": 0.3, "fiber": 2.6, "sugar": 12.2, "sodium": 1, "tags": ["banana", "kela", "fruit"]},
]
